# 蓝牙
CONFIG_ZMK_BLE=y
CONFIG_BT_DEVICE_NAME="batoid"
CONFIG_BT_BAS=y

# 休眠
CONFIG_ZMK_IDLE_SLEEP_DEPTH=1
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# 深度睡眠唤醒后自动重新广播
CONFIG_ZMK_BLE_SOFT_ON=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y

# 存储
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_BT_SETTINGS=y
